"""add unilog tables

Revision ID: 7b489712e301
Revises: 6f534f03ce89
Create Date: 2026-08-14 11:55:12.224197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '7b489712e301'
down_revision: Union[str, Sequence[str], None] = '6f534f03ce89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unilogrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mfg_part_num', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('e1_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unilog_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dib_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('part_manuf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unilogrecord_mfg_part_num'), 'unilogrecord', ['mfg_part_num'], unique=False)
    op.create_table('unilogenriched',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('enriched_data', sa.JSON(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['unilogrecord.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unilogenriched_quality_score'), 'unilogenriched', ['quality_score'], unique=False)
    op.create_index(op.f('ix_unilogenriched_record_id'), 'unilogenriched', ['record_id'], unique=False)
    op.drop_index(op.f('ix_attributeevidence_extraction_method'), table_name='attributeevidence')
    op.drop_index(op.f('ix_cacheentry_cache_key'), table_name='cacheentry')
    op.create_index(op.f('ix_cacheentry_cache_key'), 'cacheentry', ['cache_key'], unique=False)
    op.alter_column('document', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('document', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_enrichmentresult_product_status'), table_name='enrichmentresult')
    op.alter_column('processingjob', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('processingjob', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('processingjob', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('processingstep', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('processingstep', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('processingstep', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint(op.f('processingstep_job_id_fkey'), 'processingstep', type_='foreignkey')
    op.drop_constraint(op.f('processingstep_document_id_fkey'), 'processingstep', type_='foreignkey')
    op.drop_constraint(op.f('processingstep_product_id_fkey'), 'processingstep', type_='foreignkey')
    op.create_foreign_key(None, 'processingstep', 'product', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'processingstep', 'processingjob', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'processingstep', 'document', ['document_id'], ['id'], ondelete='SET NULL')
    op.alter_column('product', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('product', 'features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('product', 'applications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('product', 'certifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('product', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('product', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_product_category_status'), table_name='product')
    op.create_index(op.f('ix_product_quality_score'), 'product', ['quality_score'], unique=False)
    op.drop_index(op.f('ix_productattribute_product_confidence'), table_name='productattribute')
    op.drop_index(op.f('ix_productattribute_product_name'), table_name='productattribute')
    op.drop_index(op.f('ix_productattribute_source_type'), table_name='productattribute')
    op.drop_index(op.f('ix_validationresult_product_status'), table_name='validationresult')
    op.drop_index(op.f('ix_validationresult_severity'), table_name='validationresult')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_validationresult_severity'), 'validationresult', ['severity'], unique=False)
    op.create_index(op.f('ix_validationresult_product_status'), 'validationresult', ['product_id', 'status'], unique=False)
    op.create_index(op.f('ix_productattribute_source_type'), 'productattribute', ['source_type'], unique=False)
    op.create_index(op.f('ix_productattribute_product_name'), 'productattribute', ['product_id', 'attribute_name'], unique=False)
    op.create_index(op.f('ix_productattribute_product_confidence'), 'productattribute', ['product_id', 'confidence'], unique=False)
    op.drop_index(op.f('ix_product_quality_score'), table_name='product')
    op.create_index(op.f('ix_product_category_status'), 'product', ['category', 'status'], unique=False)
    op.alter_column('product', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('product', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('product', 'keywords',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('product', 'certifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('product', 'applications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('product', 'features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('product', 'attributes',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(None, 'processingstep', type_='foreignkey')
    op.drop_constraint(None, 'processingstep', type_='foreignkey')
    op.drop_constraint(None, 'processingstep', type_='foreignkey')
    op.create_foreign_key(op.f('processingstep_product_id_fkey'), 'processingstep', 'product', ['product_id'], ['id'])
    op.create_foreign_key(op.f('processingstep_document_id_fkey'), 'processingstep', 'document', ['document_id'], ['id'])
    op.create_foreign_key(op.f('processingstep_job_id_fkey'), 'processingstep', 'processingjob', ['job_id'], ['id'])
    op.alter_column('processingstep', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processingstep', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processingstep', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('processingjob', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('processingjob', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('processingjob', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_index(op.f('ix_enrichmentresult_product_status'), 'enrichmentresult', ['product_id', 'status'], unique=False)
    op.alter_column('document', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('document', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index(op.f('ix_cacheentry_cache_key'), table_name='cacheentry')
    op.create_index(op.f('ix_cacheentry_cache_key'), 'cacheentry', ['cache_key'], unique=True)
    op.create_index(op.f('ix_attributeevidence_extraction_method'), 'attributeevidence', ['extraction_method'], unique=False)
    op.drop_index(op.f('ix_unilogenriched_record_id'), table_name='unilogenriched')
    op.drop_index(op.f('ix_unilogenriched_quality_score'), table_name='unilogenriched')
    op.drop_table('unilogenriched')
    op.drop_index(op.f('ix_unilogrecord_mfg_part_num'), table_name='unilogrecord')
    op.drop_table('unilogrecord')
    # ### end Alembic commands ###
