"""add unilog review columns

Revision ID: e65011730e44
Revises: 7b489712e301
Create Date: 2026-08-14 12:42:20.578295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e65011730e44'
down_revision: Union[str, Sequence[str], None] = '7b489712e301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unilogenriched', sa.Column('needs_review', sa.Boolean(), nullable=False))
    op.add_column('unilogenriched', sa.Column('explainability_trace', sa.JSON(), nullable=False))
    op.add_column('unilogenriched', sa.Column('validation_flags', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_unilogenriched_needs_review'), 'unilogenriched', ['needs_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unilogenriched_needs_review'), table_name='unilogenriched')
    op.drop_column('unilogenriched', 'validation_flags')
    op.drop_column('unilogenriched', 'explainability_trace')
    op.drop_column('unilogenriched', 'needs_review')
    # ### end Alembic commands ###
